name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Moving build to artifacts directory
      run: ${{ env.GITHUB_WORKSPACE }}/buildDockerImage.sh -v 18.4.0 -x
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.DOCKER_USERNAME }}
        # Container registry password
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Container registry server url
        login-server: https://index.docker.io/v1/
